# [[dependency]]
# notation = "package:name:version"
# transitive = boolean (default: true)
# deobf = boolean (default: false)
# compile = boolean (default: true)
# run = boolean (default: true)
#
# deobf -> deobfCompile, run -> compile, !compile -> runtime, !run -> compileOnly

[[dependency]]
notation = "mcjty.theoneprobe:TheOneProbe-1.12:1.12-1.4.28-17"
transitive = false
deobf = true

[[dependency]]
notation = "mezz.jei:jei_1.12.2:4.11+"

[[dependency]]
notation = "net.sengir.forestry:forestry_1.12.2:5.8.0.+"
deobf = true
transitive = false

[[dependency]]
notation = "industrial-foregoing:industrialforegoing-1.12.2:1.10.1:176"
transitive = false
run = false

[[dependency]]
notation = "net.ndrei:tesla-core-lib:1.12-1.0.13.8"
transitive = false
run = false

[[dependency]]
notation = "net.shadowfacts:Forgelin:1.6.0+"
compile = false

[[dependency]]
notation = "com.jaquadro.minecraft.chameleon:Chameleon:1.12-4.1.3:deobf"
run = false

[[dependency]]
notation = "com.jaquadro.minecraft.storagedrawers:StorageDrawers:1.12.2-5.3.6:deobf"
run = false

[[dependency]]
notation = "com.mod-buildcraft:buildcraft-api:7.99.17"
deobf = true
provided = true

[[dependency]]
notation = "team.chisel:Chisel:MC1.12.2-0.2.1.35"
run = false

[[dependency]]
notation = "team.chisel.ctm:CTM:MC1.12.2-0.3.3.22"
provided = true

[[dependency]]
notation = "com.shinoow.abyssalcraft:AbyssalCraft:1.12.2-1.9.13.1"
deobf = true
