modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/DrManganese/TOPAddons/issues"
license="LGPL https://raw.githubusercontent.com/DrManganese/TOPAddons/master/LICENSE"

[[mods]]
modId="topaddons"
version="${file.jarVersion}"
displayName="TOP Addons"
updateJSONURL="https://raw.githubusercontent.com/DrManganese/TOPAddons/main/FUC.json"
displayURL="https://minecraft.curseforge.com/projects/top-addons"
logoFile="topaddonslogo.png"
credits="McJty, for making The One Probe"
authors="DrManganese,discolight99"
description="The One Probe integration for various mods"

[[dependencies.topaddons]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.topaddons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.topaddons]]
    modId="theoneprobe"
    mandatory=true
    versionRange="[1.18-5.0.2,)"
    ordering="AFTER"
    side="BOTH"
