modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/DrManganese/TOPAddons/issues"
license="GPLv3 https://raw.githubusercontent.com/DrManganese/TOPAddons/1.18/LICENSE"

[[mods]]
modId="topaddons"
version="${file.jarVersion}"
displayName="TOP Addons"
updateJSONURL="https://raw.githubusercontent.com/DrManganese/TOPAddons/main/FUC.json"
displayURL="https://minecraft.curseforge.com/projects/top-addons"
logoFile="topaddonslogo.png"
credits="McJty, for making The One Probe"
authors="DrManganese,discolight99"
description="The One Probe integration for various mods"

[[dependencies.topaddons]]
    modId="forge"
    mandatory=true
    versionRange="[44.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.topaddons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.topaddons]]
    modId="theoneprobe"
    mandatory=true
    versionRange="[1.19.3-7.0.0,)"
    ordering="AFTER"
    side="BOTH"
